set fallback
set windows-shell := ["pwsh.exe", "-NoLogo", "-Command"]

# Lists all available recipes
@default:
  just --list

install-caddy:
  sudo dnf install 'dnf-command(copr)'
  sudo dnf copr enable @caddy/caddy
  sudo dnf install caddy


